traPtitech/traPortfolio

docs/swagger/traPortfolio.v1.yaml

swagger のserversを変更

---

.github/workflows/main.yaml

set-envは動かなくなったので変えています
ref
https://qiita.com/shonansurvivors/items/f256a0443d346f09448e
https://q.trap.jp/messages/afd64f82-04de-4263-931b-4f7717dee087

Update deprecated workflow syntax

---

docs/swagger/traPortfolio.v1.yaml

EventAPIのレスポンスにidが含まれていなかったので，追加しました

eventにidを追加

---

docs/swagger/traPortfolio.v1.yaml

refs traPtitech/traPortfolio-UI#23

プロジェクトと班の期間を半期ごとに

---

docs/swagger/traPortfolio.v1.yaml

nullable、扱いが大変っぽい+`until`を`nullable`として書くのが結構難しそうだったので
refs https://qiita.com/sakuraya/items/2d98c352c74ad72e2a9a
破壊的変更だけどまだ実装されてないはず

nullableをoptionalに変更

---

.github/workflows/main.yaml

対応されて問題なくなった
https://github.com/k1LoW/tbls/blob/master/CHANGELOG.md#v1480-2021-01-16
https://github.com/k1LoW/tbls/blob/e3c98d4efd1865e8278c7224880ee1b024c41bc0/drivers/mysql/mysql.go#L84
refs #30

tblsのバージョン固定を解除

---

docs/swagger/traPortfolio.v1.yaml

POSTにresponseを追加

---

infrastructure/router.go
infrastructure/traQ.go
infrastructure/wire.go
infrastructure/wire_gen.go
interfaces/external/traQ.go
interfaces/repository/traQ_impl.go

traQtokenの廃止

---

domain/user.go
infrastructure/router.go
interfaces/handler/project.go
interfaces/handler/user.go
interfaces/handler/util.go
interfaces/repository/user_impl.go
usecases/repository/user_repository.go
usecases/service/user.go

feat GET /users/:userID/projects

---

domain/user.go
infrastructure/router.go
interfaces/handler/user.go
interfaces/repository/user_impl.go
usecases/repository/user_repository.go
usecases/service/user.go

実装しました
contests周りこれまで書いたことなかったのでもしかしたら欲しい情報違うかもしれないです

feat GET /users/:userID/contests

---

docs/swagger/traPortfolio.v1.yaml
infrastructure/router.go
interfaces/handler/contest.go
usecases/repository/contest_repository.go
usecases/service/contest.go

feat GET /contests/:contestID/teams

---

docs/swagger/traPortfolio.v1.yaml
infrastructure/router.go
interfaces/handler/project.go

swagger少し書き換えました
命名やや適当になってますが変えた方がよかったら言ってください:pray:
https://q.trap.jp/messages/f14fa3d9-c312-4410-8619-e62621e8be54

fix swagger改正

---

infrastructure/portal.go
infrastructure/sqlhandler.go
interfaces/database/sqlhandler.go
interfaces/external/knoq.go
interfaces/external/portal.go
interfaces/external/traQ.go
interfaces/repository/portal_impl.go
usecases/repository/contest_repository.go
usecases/repository/event_repository.go
usecases/repository/mock_repository/mock_contest_repository.go
usecases/repository/mock_repository/mock_event_repository.go
usecases/repository/mock_repository/mock_project_repository.go
usecases/repository/mock_repository/mock_user_repository.go
usecases/repository/portal_repository.go
usecases/repository/traQ_repository.go
usecases/repository/user_repository.go

refactor interfacesのmethodに引数名を追加

---

usecases/service/project.go
usecases/service/project_test.go
util/optional/time.go

usecases/service/project.goのテストを追加しました、空いてる時にレビューお願いします:pray:
`func TestProjectService_CreateProject(t *testing.T)`でやや妥協してるので何とか出来たらここどうにかしたいです

💚 Add project_test.go

---

Makefile

:rocket: make golanci-lintをgo runで実行する

---

dev/bin/up-test-db.sh

https://hub.docker.com/_/mariadb
多分サポート切れてるのか動かなかったのでdocker-compose.ymlと合わせました

:up: Update test-mariadb to 1.6.4

---

docs/swagger/traPortfolio.v1.yaml
domain/traQ.go
interfaces/external/mock_external/mock_traQ.go
interfaces/repository/traQ_impl_test.go
interfaces/repository/user_impl_test.go
usecases/service/user_test.go

- interfaces/repository/traQ_impl.goのテストを書きました
- マジックナンバーになっていたTraqStateを変数にしました
- traQに合わせて停止->凍結としました
- これに伴いSwaggerの修正が入っています

traq api test

---

infrastructure/wire_gen.go
interfaces/repository/contest_impl.go
interfaces/repository/portal_impl.go
usecases/repository/mock_repository/mock_portal_repository.go
usecases/repository/portal_repository.go

ここだけほかのrepository層と依存関係が違ってテストが書きにくかったので変更しました

:recycle: ContestRepository.portalの型を変更

---

domain/group.go
infrastructure/router.go
interfaces/handler/user.go
interfaces/repository/user_impl.go
usecases/repository/mock_repository/mock_user_repository.go
usecases/repository/user_repository.go
usecases/service/mock_service/mock_user.go
usecases/service/user.go

commit branch get-groups partially

---

infrastructure/knoq.go

:bug: 開発環境用のモジュールを間違えていた

---

interfaces/handler/user.go
usecases/service/user.go

Close #207
- :bug: accountIDとuserIDの順番が間違っていた
- :recycle: userIDがaccountIDより早く来るようにした

:bug: userIDとaccountIDの順番を他と合わせる

---

interfaces/repository/contest_impl.go
interfaces/repository/contest_impl_test.go
interfaces/repository/event_impl.go
interfaces/repository/project_impl.go
interfaces/repository/project_impl_test.go
interfaces/repository/user_impl.go
interfaces/repository/user_impl_test.go

Fix #120
- :recycle: Use Where in user_impl
- :recycle: Use Where in project_impl
- :recycle: Use Where in event_impl
- :recycle: Use Where in contest_impl
- :art: Add ln to chain
- :recycle: Use Where in DeleteAccount

Conditionの指定を修正する

---

.golangci.yml
interfaces/repository/contest_impl_test.go
interfaces/repository/event_impl_test.go
interfaces/repository/project_impl_test.go
interfaces/repository/testutil_test.go
interfaces/repository/user_impl_test.go
usecases/service/contest_test.go
usecases/service/event_test.go
usecases/service/project_test.go
usecases/service/user_test.go

- :wrench: Add linter testpackage
- :recycle: repository -> repository_test
- :recycle: service -> service_test

add test suffix

---

interfaces/repository/contest_impl.go
interfaces/repository/contest_impl_test.go

:recycle: 存在しないcontestのteamsにエラーを出す

---

docs/swagger/traPortfolio.v1.yaml
infrastructure/traq.go
interfaces/external/mock_external/mock_traq.go
interfaces/external/mock_external_e2e/mock_traq.go
interfaces/external/traq.go
interfaces/handler/types_gen.go
interfaces/handler/user.go
interfaces/handler/user_test.go
interfaces/repository/contest_impl_test.go
interfaces/repository/testutil_test.go
interfaces/repository/user_impl.go
interfaces/repository/user_impl_test.go
usecases/repository/mock_repository/mock_user_repository.go
usecases/repository/user_repository.go
usecases/service/event.go
usecases/service/event_test.go
usecases/service/mock_service/mock_user.go
usecases/service/user.go
usecases/service/user_test.go

Close #176
- :sparkles: Add GetUsers queries
- :sparkles: 引数の追加

Get /usersのQueryParamを設定する

---

interfaces/external/mock_external_e2e/mock_traq.go

:adhesive_bandage: Fix MockTraqAPI.GetAll

---

interfaces/handler/contest.go
interfaces/handler/event.go
interfaces/handler/group.go
interfaces/handler/project.go
interfaces/handler/user.go

:recycle: Cast to handler.Context

---

infrastructure/sqlhandler.go
integration_tests/testutils/db.go
util/config/config.go
util/config/config_test.go
util/config/testdata/config.yaml

Not Foundが表示されるのが微妙だと思ったのでデフォルトでは表示しないようにしました

Add Gorm config

---

docs/swagger/traPortfolio.v1.yaml
integration_tests/handler/user_test.go
interfaces/handler/contest.go
interfaces/handler/contest_test.go
interfaces/handler/event.go
interfaces/handler/group.go
interfaces/handler/oapi_types_gen.go
interfaces/handler/project.go
interfaces/handler/router.go
interfaces/handler/user.go

- :memo: Fix swagger (Post->Add,Create Account->UserAccount)
- :recycle: Sync with swagger

openapiのoperationIdの一部変更、handlerのmethod群と名前を同期

---

interfaces/repository/contest_impl_test.go
interfaces/repository/event_impl_test.go
interfaces/repository/project_impl_test.go
interfaces/repository/testutil_test.go
interfaces/repository/user_impl_test.go

- :recycle: Use exact match (test failed)
- :white_check_mark: Fix tests

repositoryテストのsqlクエリの修正

---

README.md
dev/config.yaml
main.go

development modeでモックデータを入れる

---

README.md
dev/config.yaml
main.go
util/config/config.go
util/config/config_test.go
util/config/testdata/config.yaml

close #306
production=falseでモックデータを入れるのをやめて、insert mock dataオプションにした

insert mock data オプションの追加

---

integration_tests/testutils/config.go
util/config/config.go

:bug: 結合テスト時にフラグから設定を読み込まないようにする

---

integration_tests/handler/user_test.go
integration_tests/testutils/assert.go
interfaces/handler/user.go
interfaces/repository/user_impl.go
interfaces/repository/user_impl_test.go

:recycle: Fix deleteaccount process & test

---

usecases/service/user_test.go

https://github.com/H1rono/traPortfolio/blob/2bb9431dd1327b8b15a835fa45b5617d3a237915/usecases/service/user_test.go#L652-L714

GetGroupsByUserIDのservice層のテストを作成しました

---

interfaces/repository/user_impl_test.go

https://github.com/H1rono/traPortfolio/blob/f90b7a66ec107795a3bee78e82efc5e44dac217f/interfaces/repository/user_impl_test.go#L1136-L1209

GetGroupsByUserIDのrepository層のテストを追加しました #224

---

docs/swagger/traPortfolio.v1.yaml
integration_tests/handler/user_test.go
interfaces/handler/event_test.go
interfaces/handler/oapi_types_gen.go
interfaces/handler/user_test.go

- :recycle: Add Request suffix to request-schema
- :recycle: swap schemas

リクエストボディのSchema名に-Requestを付ける

---

Makefile
README.md

- :sparkles: Add mod
- :recycle: Fix lint command
- :recycle: Fix tbls command
- :recycle: Fix go-gen command
- :sparkles: Add migrate commmand
- :sparkles: Add openapi-lint & check command
- :fire: conbine .PHONY
- :recycle: Unify brancket
- :memo: Update README

Makefileのリファクタ

---

interfaces/handler/group.go
interfaces/handler/group_test.go

successケースにSemesterとYearが反転するバグがあります　原因はわかりませんでした

GetGroup テスト書いた

---

.github/workflows/main.yaml
.golangci.yml
Makefile
README.md
docs/architecture.md
integration_tests/handler/event_test.go
integration_tests/handler/handler_test.go
integration_tests/handler/ping_test.go
integration_tests/handler/user_test.go
integration_tests/repository/contest_test.go
integration_tests/repository/event_test.go
integration_tests/repository/project_test.go
integration_tests/repository/testutil_db_test.go
integration_tests/repository/user_test.go
integration_tests/testutils/assert.go
integration_tests/testutils/config.go
integration_tests/testutils/db.go
integration_tests/testutils/router.go
interfaces/handler/export.go

ref #350
とりあえずconvertErrorは使ったままにしてます

結合テストのbuild tagsを外す

---

integration_tests/handler/event_test.go
interfaces/handler/event.go
interfaces/repository/event_impl.go

event.goに処理追加/EditEventの結合テストを1つ追加

---

interfaces/handler/contest_test.go
interfaces/handler/event_test.go
interfaces/handler/group_test.go
interfaces/handler/user_test.go

golangci-lintのアップデート？で大量にwarningが出ていたので

:rotating_light: replace unused param with underscore

---

.github/workflows/main.yaml

- :sparkles: separate unit/initegration tests

単体テストと結合テストを別のjobにする

---

.github/workflows/main.yaml

- :zap: mod->save-cache->build->save-cache(failed)からmod->build->save-cacheにする
間接的にmodのchack-latestがなくなってます

バイナリのキャッシュが行われてなかった

---

interfaces/repository/project_impl.go
interfaces/repository/project_impl_test.go

https://github.com/traPtitech/traPortfolio/issues/380

POST /projects/:projectID/membersでメンバーの重複チェックを追加

---

docs/swagger/traPortfolio.v1.yaml
domain/project.go
integration_tests/repository/project_test.go
integration_tests/repository/testutil_db_test.go
integration_tests/repository/user_test.go
interfaces/handler/project_test.go
interfaces/repository/project_impl.go
interfaces/repository/project_impl_test.go
usecases/repository/mock_repository/mock_project_repository.go
usecases/repository/project_repository.go
usecases/service/mock_service/mock_project.go
usecases/service/project.go
usecases/service/project_test.go

https://github.com/traPtitech/traPortfolio/issues/366

domain.Projectとdomain.ProjectDetailを切り分ける

---

usecases/service/group_test.go

group service/repositoryの単体テスト

---

infrastructure/wire.go
interfaces/external/knoq.go
interfaces/external/portal.go
interfaces/external/traq.go
usecases/repository/contest_repository.go
usecases/repository/event_repository.go
usecases/repository/group_repository.go
usecases/repository/project_repository.go
usecases/repository/user_repository.go

:recycle: go:generateのバージョン統一

---

util/random/random.go

domainLengthの型をintにした

---

.github/workflows/main.yaml

:bug: 多分job分けたせいでcodecovバグったので同じjobでアップロードする

---

domain/group.go
domain/project.go
domain/user.go
integration_tests/repository/project_test.go
integration_tests/repository/user_test.go
interfaces/handler/group.go
interfaces/handler/group_test.go
interfaces/handler/project.go
interfaces/handler/project_test.go
interfaces/handler/user_test.go
interfaces/repository/group_impl.go
interfaces/repository/group_impl_test.go
interfaces/repository/project_impl.go
interfaces/repository/project_impl_test.go
interfaces/repository/user_impl.go
interfaces/repository/user_impl_test.go
usecases/repository/mock_repository/mock_project_repository.go
usecases/repository/mock_repository/mock_user_repository.go
usecases/repository/project_repository.go
usecases/repository/user_repository.go
usecases/service/group.go
usecases/service/group_test.go
usecases/service/mock_service/mock_project.go
usecases/service/mock_service/mock_user.go
usecases/service/project.go
usecases/service/project_test.go
usecases/service/user.go
usecases/service/user_test.go

UserGroupとGroupUserの名前を交換

---

infrastructure/migration/migrate.go

:recycle: use specified tables

---

integration_tests/handler/contest_test.go
interfaces/handler/contest.go
interfaces/repository/contest_impl.go
interfaces/repository/contest_impl_test.go
util/mockdata/consts.go
util/mockdata/handler.go
util/mockdata/model.go

https://github.com/traPtitech/traPortfolio/issues/339
>分量が多いのでGetContestTeamMemberから下を自分がやります
って書いてあったのでとりあえずその分だけやりました

contest handlerの結合テスト(後半部分)

---

util/random/random.go

:recycle: use sort in random.Duration

---

infrastructure/sqlhandler.go
integration_tests/handler/contest_test.go
interfaces/database/errors.go
interfaces/repository/error.go

close https://github.com/traPtitech/traPortfolio/issues/424
これを参考にしました
https://github.com/go-gorm/gorm/issues/4037#issuecomment-881834378

外部キー制約エラーを変換

---

infrastructure/knoq.go
infrastructure/portal.go
infrastructure/sqlhandler.go
infrastructure/traq.go
interfaces/database/mock_database/mock_sqlhandler.go
interfaces/handler/user.go
interfaces/repository/contest_impl.go
interfaces/repository/event_impl.go
interfaces/repository/group_impl.go
interfaces/repository/project_impl.go
interfaces/repository/user_impl.go

ref: #233
- :recycle: SQLHandler: simplify receiver name
- :recycle: ExternalAPI: simplify receiver name
- :recycle: MockSQLHandler: simplify receiver name
- :recycle: UserHandler: simplify receiver name
- :recycle: Repository: simplify receiver name

レシーバ名を一文字にした

---

interfaces/repository/contest_impl_test.go

テストでValueOrZeroを使う

---

integration_tests/handler/contest_test.go
integration_tests/handler/event_test.go
integration_tests/handler/group_test.go
integration_tests/handler/project_test.go
integration_tests/handler/user_test.go
interfaces/handler/context.go
interfaces/handler/errors.go

close #427
- :zap: add error info to ErrBind/ErrValidate
- :zap: change error response & add internal error message
- :bug: integration-test: fix error response messages

エラーレスポンスにエラー詳細を追加する

---

integration_tests/handler/contest_test.go

TestAddContestTeam エラーケース3つ書いた

---

interfaces/repository/user_impl_test.go

🩹 add with args to missing

---

integration_tests/handler/contest_test.go

TestEditContestTeamのintegration test 7つ書いた

---

integration_tests/handler/contest_test.go
interfaces/repository/user_impl.go
interfaces/repository/user_impl_test.go
util/mockdata/consts.go
util/mockdata/handler.go
util/mockdata/model.go

- :bug: fix userContest logic
- :bug: quit edit one user concurrently

テストで同じコンテストの情報を同時に変更しないようにする

---

integration_tests/handler/user_test.go
interfaces/handler/user_test.go
interfaces/handler/validator.go

GetUserParamsにlimitのルール追加

---

interfaces/repository/user_impl_test.go

`(*UserRepository).UpdateAccount`のテスト修正

---

integration_tests/repository/contest_test.go
integration_tests/repository/project_test.go
integration_tests/repository/user_test.go
usecases/service/contest_test.go
usecases/service/user_test.go
util/optional/of.go
util/random/repository.go

#395 (これでcloseするか要検討)
optionalにも足した

random関数とテストケースを追加

---

integration_tests/repository/contest_test.go
integration_tests/repository/project_test.go
integration_tests/repository/user_test.go
interfaces/repository/project_impl.go
interfaces/repository/user_impl.go
usecases/service/project_test.go
util/optional/of.go

```go
func (o Of[T]) ValueOr(v T) T
```
書きたくなったので書きました

`Of.ValueOr`を追加

---

codecov.yml

close #558 数字はテキトーです
Project Statusはコード全体のステータス、Patch StatusはcommitまたはPRで変更された部分のステータスを表します。`target`はステータスが`success`となる最小の割合、`threshold`は許容できる低下率です。

:wrench: Configure codecov coverage status

---

interfaces/handler/router.go
main.go

:sparkles: add EnableLogger option

---

.github/workflows/staging.yaml

:wrench: Modify staging script

---

.github/workflows/release.yaml
.github/workflows/staging.yaml

https://github.com/traPtitech/traPortfolio/actions/runs/7382851383 落ちてたやつの修正
ref: [github actions - ERROR: denied: installation not allowed to Create organization package - Stack Overflow](https://stackoverflow.com/questions/76607955/error-denied-installation-not-allowed-to-create-organization-package)

:wrench: Modify GHA permission

---

.github/dependabot.yml

🎨 improve commit message

---

.github/dependabot.yml

:wrench: Configure dependabot for Dockerfile

---

codecov.yml

:wrench: remove project target coverage

---

cmd/injector.go
injector.go
integration_tests/handler/0_utils_test.go
main.go

:recycle: Move injector

---

domain/user.go

https://q.trap.jp/messages/4c1beacb-234b-42d1-b2d8-c41b0a88cee0

zennのid制約を修正
