- .github/workflows/main.yaml
tblsのバージョンが上がって`generation_expression`っていうテーブルを参照するようになったみたいだけど、今使ってるmariadbだとそれがないのでtblsのバージョンを固定するように変更した(mariadb:10.2.5↑なら大丈夫そうな気がする)
> ciのtblsのバージョンを固定

- infrastructure/sqlhandler.go
gorm内部では`gorm.DB`をクローンしていて、元の`DB`には影響が及ばないようにしてあったけど、そこがうまく行ってなかったので修正した
> fix sqlhandler

- .golangci.yml
- interfaces/handler/api.go
- interfaces/repository/contest_impl.go
- interfaces/repository/event_impl.go
warning出るので削除して良さそう？です
```fish
$ make golangci-lint                                                                                                                                                            
level=warning msg="[runner] The linter 'golint' is deprecated (since v1.41.0) due to: The repository of the linter has been archived by the owner.  Replaced by revive."
```
> disable golint

- usecases/service/project_test.go
- usecases/service/user_test.go
テストのfailと紛らわしいので消しました
https://golang.org/src/testing/testing_test.go とか見ても命名規則バラバラなので何がいいかよくわかってないです
> :art: Remove subtests' prefix "Fail_"

- infrastructure/sqlhandler.go
- interfaces/database/mock_database/mock_sqlhandler.go
- interfaces/database/sqlhandler.go
- interfaces/handler/event.go
- interfaces/repository/event_impl.go
- interfaces/repository/event_impl_test.go
- interfaces/repository/model/event.go
- usecases/repository/event_repository.go
- usecases/repository/mock_repository/mock_event_repository.go
- usecases/service/event.go
- usecases/service/event_test.go
Closes #142 
- [Update](https://gorm.io/ja_JP/docs/update.html#%E5%8D%98%E4%B8%80%E3%81%AE%E3%82%AB%E3%83%A9%E3%83%A0%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%99%E3%82%8B)を使ってlevelカラムだけを変更
- `(repository.UpdateEventArg).Level`がゼロ値でも問題なくなったのでポインタ型やめた
- 存在確認した時にすでに変更したいのと同じLevelがDBに入っていたらUpdateせずに終わるようにした
- エラーハンドリングをちょっと追加した
- テスト書いた
好みかもですが`UpdateEvent`より`UpdateEventLevel`のほうがいいかなと思いましたが迷ったので変更してないです
> Fix repository.UpdateEvent

- docs/swagger/traPortfolio.v1.yaml
- PostとPatchで同じschemaを使ってたのを別のものを使うように
- `format: url`と`format: uri`が混在していたので[Data Types](https://swagger.io/docs/specification/data-models/data-types/)に載ってたuriの方を採用
- allOfで要素が一つしかないものを直接refで参照
- 後に自動生成する際に無名の構造体が生成されて扱いにくいため
- descriptionが更新できなくなるのでやや妥協案ですが、、、
- typo修正
> :books: Fix Openapi

- interfaces/repository/contest_impl_test.go
- interfaces/repository/event_impl.go
- interfaces/repository/event_impl_test.go
- interfaces/repository/project_impl_test.go
- interfaces/repository/user_impl.go
- interfaces/repository/user_impl_test.go
- usecases/repository/mock_repository/mock_user_repository.go
- :recycle: Change mockXXXRepositoryFields's fields type
- :recycle: rename api to knoq
> mockEventRepositoryFields等のfieldをinterfaceからstructにする

- main.go
- util/config/config.go
https://github.com/traPtitech/traPortfolio/blob/2c6d93ea40e68a72d5f16aeb8a181e891e4a8ba8/integration_tests/handler/main_test.go#L21-L27 などで環境変数の読み込みが分散するのが気になったので移行しました
> :recycle: 環境変数の読み込みをconfig.goに移行

- usecases/service/user_test.go
- :white_check_mark: Fix id name
- :bug: swap userID and accountID
> userIDとaccountIDの順番が逆になっているテストを修正

- dev/config.yaml
- integration_tests/handler/user_test.go
- interfaces/external/mock_external_e2e/mock_knoq.go
- interfaces/repository/user_impl.go
- interfaces/repository/user_impl_test.go
- util/mockdata/handler.go
- :boom: CloneHandlerMockUserXXX -> CloneHandlerMockUserXXXs
- :bug: Fix assignment
- :white_check_mark: Test GetUserProjects
- :white_check_mark: Add case to TestGetUserAccounts
- :bug: Fix id assignment
- :white_check_mark: Test GetUserContests
- :white_check_mark: Test GetUserGroups
- :sparkles: Define CloneHandlerMockUserEvents & fix GetByUserID process
- :white_check_mark: Test GetUserEvents
> user.goの結合テストの続き

- integration_tests/handler/contest_test.go
- integration_tests/handler/event_test.go
- integration_tests/handler/group_test.go
- integration_tests/handler/project_test.go
- integration_tests/handler/user_test.go
- util/mockdata/consts.go
- util/mockdata/external.go
- util/mockdata/handler.go
- util/mockdata/model.go
mockdata/consts.go の 〜ID の部分をパブリックな関数にした
integration_tests の HMock〜.Id となっている部分を↑で作ったパブリックな関数にした
なんかテスト通ってないっぽい(?)ですが、比較も兼ねて一旦 PR 出します
> 結合テストの UUID の表示を変更した

- infrastructure/sqlhandler.go
- infrastructure/wire.go
- infrastructure/wire_gen.go
- integration_tests/repository/contest_test.go
- integration_tests/repository/event_test.go
- integration_tests/repository/project_test.go
- integration_tests/repository/user_test.go
- integration_tests/testutils/db.go
- integration_tests/testutils/router.go
- main.go
- :recycle: infrastructure.NewSQLHandler -> NewGormDB
- :recycle: format code
- :truck: rename FromDB -> NewSQLHandler
- :recycle: format code
> infrastructure.NewSQLHandlerには構造体のコンストラクタとしての役割だけを持たせる

- go.mod
@mehm8128 
もともとindirectで使われてたgithub.com/go-sql-driver/mysqlがdirectになったので修正しました
指摘するの忘れてたすみません:pray:
> :recycle: use github.com/go-sql-driver/mysql as direct

- docs/swagger/traPortfolio.v1.yaml
close https://github.com/traPtitech/traPortfolio/issues/440
> GET /users/:id/contestsでContestTeamの情報が返ってるのを修正

- infrastructure/wire.go
- infrastructure/wire_gen.go
- integration_tests/handler/handler_test.go
- integration_tests/repository/testutil_db_test.go
- integration_tests/testutils/config.go
- integration_tests/testutils/db.go
- main.go
- util/config/config.go
- util/config/config_test.go
- :fire: remove BindPFlag (default delimiter is ".")
- :recycle: describe const directly
- :recycle: error handling
- :recycle: use atomic.Bool to parsed flag
- :adhesive_bandage: assert error
- :recycle: improve comment
- :recycle: return clone of config
- :recycle: rename to isParsed
- :recycle: rename to flag
- :fire: remove simple method
> configのリファクタ

- util/config/config.go
- Revert ":fire: remove BindPFlag (default delimiter is ".")"
- :recycle: bint pflags with for
> tblsのjobが終わらない修正(pflagが指定できないことの修正)

- docker-compose.yml
resolves #514
手元でやったらtraportfolio-backend-1がfailしてなかったのでこれで何とかなってると思います
> docker-compose.ymlにあるsqlのhealthcheckを改善した

- infrastructure/external/apiclient.go
- infrastructure/external/knoq.go
- infrastructure/external/portal.go
- infrastructure/external/traq.go
- infrastructure/injector.go
- infrastructure/repository/db.go
- integration_tests/handler/main_test.go
- integration_tests/repository/main_test.go
- integration_tests/testutils/db.go
- main.go
- util/config/config.go
- :fire: remove (*Config).SQLConf()
- :fire: remove (*Config).TraqConf()
- :fire: remove (*Config).KnoqConf()
- :fire: remove (*Config).PortalConf()
- :fire: remove (*Traq/Knoq/PortalConfig).API()
- :fire: remove (*SQLConfig).DsnConfigWithoutName()
- :fire: remove (*Config).Addr()
> config packageの冗長なメソッドを削除

- .github/workflows/main.yaml
実は[codecov/codecov-action@v4](https://github.com/codecov/codecov-action/releases/tag/v4.0.0)からカバレッジのアップロードにTokenが必要になっていました
> Tokenless uploading is unsupported.
その対応です、H1ronoからはRepository secretsをいじれないので`CODECOV_TOKEN`を追加してからマージしてください
> :wrench: Use CODECOV_TOKEN to upload

- docs/swagger/traPortfolio.v1.yaml
- internal/handler/contest.go
- internal/handler/contest_test.go
- internal/handler/group.go
- internal/handler/group_test.go
- internal/handler/project.go
- internal/handler/project_test.go
- internal/handler/schema/schema_gen.go
- internal/handler/schema/validator.go
- internal/infrastructure/repository/contest_impl.go
- internal/infrastructure/repository/contest_test.go
- internal/infrastructure/repository/group_impl.go
- internal/infrastructure/repository/project_impl.go
- internal/infrastructure/repository/project_test.go
- internal/usecases/repository/contest_repository.go
- internal/usecases/repository/group_repository.go
- internal/usecases/repository/mock_repository/mock_contest_repository.go
- internal/usecases/repository/mock_repository/mock_group_repository.go
- internal/usecases/repository/mock_repository/mock_project_repository.go
- internal/usecases/repository/project_repository.go
close #90
eventsのスキーマにlimitを追加していますが、eventsではknoQ側のAPIにlimitがなかったため実装はしていません。
> Users以外にlimitを追加
